server:
  port: 8080

spring:
  banner:
    image:
      location: banner.txt
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    generate-ddl: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    password: admin
    username: admin
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;DATABASE_TO_UPPER=false;
  h2:
    console:
      enabled: 'true'

contacts:
  endpoint:
    url: "https://challenge.trio.dev/api/v1/"

mailchimp:
  list:
    default:
      id: "ed1c7ae58d"
  api:
    key: "e054a920262868edbcb1acfc2c13a68e-us21"